name: shann_rag
services:
  youthful_wilbur:
    container_name: youthful_wilbur
    build: .
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  amazing_kowalski:
    container_name: amazing_kowalski
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"