name: shann_rag
services:
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app_network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app_network
    depends_on:
      - backend
networks:
  app_network:
    driver: bridge
