name: shann_rag
services:
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    networks:
      - app_network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - .env
    networks:
      - app_network
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
